#!/usr/bin/env bash

if [ "$1" == "dual" ]; then
  hyprctl keyword monitor DP-1,2560x1440@120,0x0,1,vrr,2
  hyprctl keyword monitor DP-2,2560x1440@120,2560x0,1,vrr,2
  hyprctl keyword monitor DP-3,1920x1080@144,1600x-1080,1
elif [ "$1" = "uw" ]; then
  hyprctl keyword monitor DP-1,5120x1440@240,0x0,1,vrr,2
  hyprctl keyword monitor DP-2,disable
  hyprctl keyword monitor DP-3,1920x1080@144,1600x-1080,1
fi
